version: "3.8"

services:
    backend:
      image: eclipse-temurin:21-jdk
      container_name: backend
      restart: always
      build:
        context: .
        dockerfile: Dockerfile-Back
      environment:
        - SPRING_PROFILES_ACTIVE=prod   
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=PA@password
      ports:
        - "8080:8080"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
        interval: 30s
        timeout: 10s
        retries: 5
      volumes:
        - backend_data:/app/data


volumes:
  backend_data:
    driver: local
