FROM python:latest
WORKDIR /app
RUN apt-get update && apt-get install -y python3-venv python3-pip
RUN python3 -m venv venv
ENV PATH="/app/venv/bin:$PATH"
RUN pip install flask
COPY . .
EXPOSE 5000
CMD ["python", "app.py"]
