version: '3.9'
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # monta o código local no /app do contêiner

