# Usa uma imagem leve do Node.js com Alpine Linux
FROM node:18-alpine

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos da aplicação Angular para o diretório de trabalho
COPY ./hackaton-front/nexusCareFront/ /app/

# Instala dependências do sistema para compilar pacotes nativos, se necessário
RUN apk add --no-cache git python3 make g++
EXPOSE 4200
# Instala as dependências
RUN npm install
CMD ["npm", "run", "start-docker","ng server"]
