version: '3.8'

services:
  angular-app:  # Este é o nome do serviço - ele não deve ser "frontend" no nível raiz
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:4200"
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    command: npm start
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  node_modules:
