version: '3.8'

services:
  angular-app:
    build:
      context: .                          # <- Agora o Docker vê tudo a partir da raiz
      dockerfile: Dockerfile-Front        # <- Dockerfile permanece fora da pasta do app
    ports:
      - "80:4200"
    volumes:
      - ./hackaton-front/nexusCareFront:/app
      - node_modules:/app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  node_modules:
