- name: Instalar Docker e Rodar Postgres
  hosts: all
  remote_user: root
  tasks:
  - name: Instalar pré-requisitos
    shell: |
      echo "Inciando script"
       yum update -y
       yum install -y curl
       yum install -y docker
       service docker start
       usermod -a -G docker ec2-user
       curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
       chmod +x /usr/local/bin/docker-compose
       docker-compose version
       docker ps 
  - name: Rodar Postgres
    shell: |
        echo "Rodando Docker Compose com postgres.yml"
        docker-compose -f /home/ec2-user/docker-tf/Docker-Db/postgres.yml up -d
    args:
        chdir: "{{ playbook_dir }}"
        executable: /bin/bash
  - name: Rodar Back
    shell: |
        echo "Rodando Docker compose flask.yml"
        docker-compose -f /home/ec2-user/docker-tf/Docker-Back/flask.yml up -
