---
- name: Instalar Docker, Docker Compose e rodar containers
  hosts: all
  become: true
  vars:
    docker_compose_path: /usr/local/bin/docker-compose
    postgres_compose_file: /home/ec2-user/docker-tf/Docker-Db/postgres.yml
    flask_compose_file: /home/ec2-user/docker-tf/Docker-Back/flask.yml

  tasks:
    - name: Atualizar pacotes
      yum:
        name: "*"
        state: latest

    - name: Instalar dependências
      yum:
        name:
          - curl
          - docker
        state: present

    - name: Iniciar e habilitar o serviço Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Adicionar usuário ec2-user ao grupo docker
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Instalar Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
        dest: "{{ docker_compose_path }}"
        mode: '0755'

    - name: Verificar versão do Docker Compose
      command: docker-compose --version
      register: compose_version
      changed_when: false

    - debug:
        var: compose_version.stdout

    - name: Rodar PostgreSQL com docker-compose
      docker_compose:
        project_src: "{{ postgres_compose_file | dirname }}"
        files:
          - "{{ postgres_compose_file }}"
        state: present

    - name: Rodar Backend Flask com docker-compose
      docker_compose:
        project_src: "{{ flask_compose_file | dirname }}"
        files:
          - "{{ flask_compose_file }}"
        state: present
